workflows:
  crown-workflow:
    name: Crowns Sequence Mastery
    max_build_duration: 120
    integrations:
      app_store_connect: CrownSequanceCodemagicKey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.crown.sequancemastery
      vars:
        APP_STORE_APPLE_ID: 6740202427
        BUNDLE_ID: 'com.crown.sequancemastery'
        XCODE_WORKSPACE: 'CrownSequenceMastery.xcworkspace'
        CODE_SCHEME: 'CrownSequenceMastery'
    scripts:
      - name: Install node modules
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profile settings on  Xcode project
        script: |
          cd ios
          xcode-project use-profiles
      - name: Increment build number
        script: |
          #!/bin/sh
          cd $CM_BUILD_DIR/ios
          # Print current values before increment
          echo "Current Info.plist values:"
          plutil -p CrownSequenceMastery/Info.plist | grep CFBundle
          
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          NEXT_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          echo "Latest build number from App Store: $LATEST_BUILD_NUMBER"
          echo "Next build number will be: $NEXT_BUILD_NUMBER"
          
          # Directly modify Info.plist instead of using agvtool
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEXT_BUILD_NUMBER" CrownSequenceMastery/Info.plist
          
          # Verify the update
          echo "Updated Info.plist values:"
          plutil -p CrownSequenceMastery/Info.plist | grep CFBundle
      - name: Set Info.plist values
        script: |
          #!/bin/sh
          PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Build ipa for distribution
        script: |
          #!/bin/sh
          echo "Building IPA with following version info:"
          plutil -p $CM_BUILD_DIR/ios/CrownSequenceMastery/Info.plist | grep CFBundle
          
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        copyright: Crowns Sequence Mastery 2024